# Dependencies
markdown:         redcarpet
highlighter:      rouge
gems: ['jekyll-paginate', 'redcarpet', 'jekyll-gist', 'rouge']

# Permalinks
permalink:        pretty
#relative_permalinks: false

# Setup
title:            FWC
tagline:          'Frankly Who Cares'
description:      'by Daniel Da Cunha.<br><a href="https://twitter.com/FranklyWhoCares" target="_blank">@FranklyWhoCares</a>.'
url:              http://franklywhocares.net
baseurl:          /

author:
  name:           'Daniel Da Cunha'
  url:            https://twitter.com/FranklyWhoCares

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ddacunha/hyde
